apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    env: qa
  name: my-app
  namespace: mlapi
spec:
  replicas: 1 # Creating PODs for our app
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        env: qa
    spec:
      containers:
      - image: de.icr.io/xaviervasques/my-kube-api:latest # Docker image name, that we uploaded
        name: my-kube-api     # POD name 
        command: ["python3", "api.py" ]
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: all-icr-io
